;;; ~/.doom.d/agenda.el -*- lexical-binding: t; -*-
(defun org-capture-template-dynamic (arg)
  "A guided walk-through to capturing"
  (interactive)
  (let ((org-agenda-files (list (buffer-file-name (current-buffer)))))
    (if (null (car org-agenda-files))
        (error "%s is not visiting a faile" (buffer-name (current-buffer)))
      (counsel-org-agenda-headlines)))
  (goto-char (org-end-of-subtree))
  (if (eq (count-lines (point-min) (point-max)) (count-lines (point-min) (point)))
      (newline-and-indent))
  (defvar option1 '("TASK" "Headline" "Checklist" "Ordered List"))
  (defvar option2 '("Active Timestamp" "In-active Timestamp" "No Timestamp"))
  (let ((selection (ivy-completing-read "Choose an option: " option1))
        (date1 (ivy-completing-read "Choose 2nd option: " option2)))
    (if (eq selection (nth 0 option1))
        (concat "* TODO "))
    (if (eq selection (nth 1 option1))
        (concat "* " string))
    (if (eq selection (nth 2 option1))
        (concat "- [ ] "))
    (if (eq selection (nth 3 option1))
        (concat "- "))
    (if (eq date1 (nth 0 option2))
        (concat (format-time-string "<%Y-%m-%d %a>")))))

; "Checks to see if the current line position is at the end of the buffer or not.")
(if (eq (count-lines (point-min) (point-max)) (count-lines (point-min) (point)))
    (newline-and-indent))
