(package! helm-org-rifle)
(package! org-journal)
(package! literate-calc-mode)
(package! org-ql)
(package! org-super-agenda)
(package! elfeed)
(package! elfeed-org)
(package! ob-mermaid)
(package! mermaid-mode)
(package! ox-reveal)
(package! chocolate-theme)
(package! quickref)
;(package! org-super-links
;  :recipe (:host github :repo "nmartin84/org-super-links"))
(package! bookmark+
  :recipe (:host github :repo "emacsmirror/bookmark-plus"))
(package! org-board)
(package! org-mind-map)
(package! ox-pandoc)
(package! ox-twbs)
(package! pdf-tools)
(package! gnuplot)
(package! gnuplot-mode)
(package! deadgrep)
(package! org-web-tools)
(package! graphviz-dot-mode)
